version: '3'

services:
  web:
    image: nginx
    ports: 
    - 80:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    ports:
      - 5432
  minha_app:
    image: jacksonpires/minha-app-dockerizada:latest
    build: .
    ports:
      - 3090
    depends_on:
      - db

